[build]
  publish = "_site"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Redirect rules for clean URLs and compatibility
[[redirects]]
  from = "/episodes/*"
  to = "/episodes/:splat"
  status = 200

# Handle RSS feed
[[redirects]]
  from = "/feed"
  to = "/feed.xml"
  status = 301

# Handle episode pages without .html extension
[[redirects]]
  from = "/:episode"
  to = "/:episode/index.html"
  status = 200
  conditions = {Role = ["admin", "editor"], Country = ["US"]}

# Fallback for SPA-like behavior (optional)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true